### ISSUE TITLE
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.ServiceProcess.TimeoutException: 

### ISSUE THREAD

**Issue by AIunusual** [wiresock/proxifyre#21]
Dear Sir,
Thank you very much for your contribution to the tool. I try to launch it by ".\ProxiFyre.exe start" in admin powerShell, but I got the following error,

"Configuration Result:
[Success] Name ProxiFyreService
[Success] DisplayName ProxiFyre Service
[Success] Description ProxiFyre - SOCKS5 Proxifier Service
[Success] ServiceName ProxiFyreService
Topshelf v4.3.0.0, .NET Framework 4.8.9181.0 (4.0.30319.42000)
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.ServiceProcess.TimeoutException: 
    System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
    Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
    Topshelf.Hosts.StartHost.Run()"
    
My system is windows 10 and I wonder could you give any opinion about what is happening? Thank you very much for your help.

**Comment by wiresock** [comment]
The primary reason for service start failures is often the absence of the Windows Packet Filter driver. To resolve this, you can download and install the suitable version from the following link: [Windows Packet Filter Driver v3.4.8](https://github.com/wiresock/ndisapi/releases/tag/v3.4.8).

**Comment by AIunusual** [comment]
Dear Vadim,

Thank you very much for your reply. I appreciate your time and effort in assisting me with my issue. I would like to inform you that I installed the Windows Packet Filter Driver v3.4.8 x64 on my x64 system before. If it's not too much trouble, could you possibly provide some insight into what other factors might be contributing to this problem? Your expertise and guidance would be greatly beneficial.

Thank you once again for your assistance.

**Comment by wiresock** [comment]
Did you create the app-config.json file and place it next to the ProxiFyre executable?

**Comment by AIunusual** [comment]
Dear Vadim, 
I found my app-config.json has Filename Extension .txt , after I fixed it then Proxifyre sucessfully lauched. Thank you very much for your assistance.
