### ISSUE TITLE
Can't compile using VS 2022

### ISSUE THREAD

**Issue by AroaR91867HTML** [wiresock/proxifyre#24]
Hello,

When doing `build` on Solution `socksify, I get 2 errors, I've looked at your documentation but don't find much info at all from the build process, I would really like to test this utility you have built but compiled myself not from binaries.

![screenshot_2024-03-06_02:01:16](https://github.com/wiresock/proxifyre/assets/161356118/93506249-6b62-4ee8-a91a-e81716138a36)

Have a good day

**Comment by wiresock** [comment]
The project requires the 'ms-gsl' package, which is a missing dependency. Please consult the 'Build Prerequisites' section in the README for instructions on how to install it.

**Comment by AroaR91867HTML** [comment]
I have already done that and didn't seem to have any error
![screenshot_2024-03-06_17:36:47](https://github.com/wiresock/proxifyre/assets/161356118/ea9f9061-b898-44fd-ad07-9d2d835e8a15)

But still the same message appears, thank you for the help truly

**Comment by AroaR91867HTML** [comment]
Nevermind, it was the vcpkg path in Visual Studio.
Last thing: The executable being output for x64 is 10KB, yours is 36KB, is there a reason?

**Comment by wiresock** [comment]
I believe the difference in the executable size that you've noticed is likely due to the digital signature.
