### ISSUE TITLE
Behavior of the config file

### ISSUE THREAD

**Issue by NN-Binary** [wiresock/proxifyre#26]
```
{
 "logLevel": "None",
 "proxies": [
         {
         "appNames": ["program.exe"],
         "socks5ProxyEndpoint": "proxy.test.com:5256",
         "supportedProtocols": ["TCP", "UDP"]
         },
         {
         "appNames": ["program.exe"],
         "socks5ProxyEndpoint": "proxy.test.com:5257",
         "supportedProtocols": ["TCP", "UDP"]
         },
     ]
}
```

1) I would like to know what is the behavior when adding **twice** the same program, does it override the previous one?
2) If I add another program with supportedProtocols: [] // Empty, does it override the previous one and remove the proxification?

**Comment by NN-Binary** [comment]
3. Is there a way to remove a proxy at runtime?

**Comment by wiresock** [comment]
1. While I haven't verified this, it's likely that two proxy instances will be created. Initially, the application should bind to the first instance, and then it would be re-bound to the second instance.

2. I haven't tested this scenario personally, but I believe that once the application is bound to the second proxy, it will bypass the proxification. It's important to note that if a proxy does not have any supported protocols listed, it will not start.

3. Currently, there's no functionality for dynamic removal of proxies implemented in the code.

**Comment by NN-Binary** [comment]
I appreciate your time
For 1. Does it mean that it will slow down performances at runtime? (not talking about the starting time).

**Comment by wiresock** [comment]
Adding an extra active proxy does introduce some overhead, yet it should not significantly impact throughput, as this proxy will remain in a wait state.
