### ISSUE TITLE
Error at startup with Server 2003 SP2

### ISSUE THREAD

**Issue by Stepman123** [wiresock/proxifyre#31]
Hello.
I tried running ProxiFyre on 2003 SP2 32-bit with One Core API. Is it possible to fix this error?

Configuration Result:
[Success] Name ProxiFyreService
[Success] DisplayName ProxiFyre Service
[Success] Description ProxiFyre - SOCKS5 Proxifier Service
[Success] ServiceName ProxiFyreService
Topshelf v4.3.0.0, .NET Framework 4.8.4526.0 (4.0.30319.42000)
Topshelf.Hosts.ConsoleRunHost Error: 0 : An exception occurred, System.Runtime.InteropServices.SEHException (0x80004005): 
...

[start error.txt](https://github.com/wiresock/proxifyre/files/14910230/start.error.txt)

**Comment by wiresock** [comment]
The Socksify C++/CLI class library, which serves as the foundation for the ProxiFyre service, has been developed using the Visual Studio 2022 platform toolset (v143). Unfortunately, this toolset lacks support for Windows XP/2003. While backporting the project to accommodate Windows XP/2003 is theoretically feasible, it seems unnecessary and potentially impractical to undertake such an effort.

**Comment by Stepman123** [comment]
> this toolset lacks support for Windows XP/2003

On Windows 7 the error is exactly the same. Maybe it will be possible to run ProxiFyre at least on Windows 7?

[w7.txt](https://github.com/wiresock/proxifyre/files/14910909/w7.txt)

**Comment by wiresock** [comment]
Have you installed Windows Packet Filter?

**Comment by Stepman123** [comment]
Thank you. After installing Windows.Packet.Filter.3.4.8.1.exe, ProxiFyre started.
The problem is that it does not redirect programs. Browsers work directly.
There is an error in the log with IP 1.1.1.1. Is this ProxiFyre DNS? Because I haven't used this anywhere.



[logfile_2024-04-09.txt](https://github.com/wiresock/proxifyre/files/14916218/logfile_2024-04-09.txt)

[app-config.json](https://github.com/wiresock/proxifyre/files/14916222/app-config.json)

**Comment by wiresock** [comment]
IP address 1.1.1.1 is utilized to identify your default internet connection. Upon determining this interface, ProxiFyre initiates filtering and redirects all connections from this interface to the SOCKS proxy. However, if your device lacks a default network connection, this method will not work.

**Comment by jonm58** [comment]
> default network connection

this?
![image](https://github.com/wiresock/proxifyre/assets/73036321/da5f608a-7bc2-472a-853a-93f785b06f3a)

**Comment by Stepman123** [comment]
> However, if your device lacks a default network connection, this method will not work.

Does this mean that if I have one active Internet connection, then this is the “default network connection”? (Internet via USB WiFi)
On Windows 7, the same error occurs if the Internet is not connected: Failed to figure out the route to the 1.1.1.1
::0
If the Internet is connected, then this error does not exist.
On Server 2003 there is an error in any case.
Why?
There are slight differences in route table 2003.

When the Internet is not connected:
![7_2003_route](https://github.com/wiresock/proxifyre/assets/8846337/91194c1f-1752-4ea6-a40f-da17fa39c34e)

When the Internet is connected:
![7_2003_route-connected](https://github.com/wiresock/proxifyre/assets/8846337/10229c67-ac3d-4a58-bf12-2c90b7d1b6ae)

**Comment by wiresock** [comment]
Yes, you're correct. ProxiFyre requires an active Internet connection to function correctly. It operates by intercepting traffic from the Internet-connected interface, and if it's unable to detect such a connection, it won't be able to function as intended.

**Comment by Stepman123** [comment]
Socksify doesn't work either, but in a different way. The browser cannot connect - connection timeout.
Socksify launches without errors.
How to understand what the reason is. Maybe Pkt Filter is not working correctly?

**Comment by wiresock** [comment]
Windows Packet Filter is widely used in commercial software, so it's unlikely to be the source of the issue. However, tools like Socksify and ProxiFyre transform outgoing packets into incoming ones, which might be blocked by a locally running firewall, including the built-in one. Consider temporarily disabling your firewall to see if this resolves the problem.

**Comment by jonm58** [comment]
> Socksify doesn't work either, but in a different way. The browser cannot connect - connection timeout. Socksify launches without errors. How to understand what the reason is. Maybe Pkt Filter is not working correctly?

OCAPI broke some app and proxy don't work,like WLM09

**Comment by Stepman123** [comment]
> Consider temporarily disabling your firewall to see if this resolves the problem.

Yes, in the case of Socksify, the reason is the Windows firewall. If the firewall is disabled, then Socksify works, but ProxiFyre reports the same error in the log.
Additionally, Socksify does not work properly. For example, some sites go directly past Socksify. I think the problem is that different sites are open in different browser tabs. It is likely that different tabs use different processes (thorium.exe) to connect, and Socksify only works with one process. Or Socksify will incorrectly determine which process should receive the incoming packet during the connection.

Above I said that ProxiFyre works in Windows 7, but in fact there was the same problem as in 2003 with Socksify.

**Comment by wiresock** [comment]
ProxiFyre is essentially an enhanced version of the socksify demo, resulting in very similar behaviors between the two. Regarding process identification, it's important to run ProxiFyre with administrative privileges. Without admin rights, ProxiFyre will only be able to identify processes that the current user has access to.
