### ISSUE TITLE
Adding appNames

### ISSUE THREAD

**Issue by ashik4u** [wiresock/proxifyre#34]
Hi, please hrelp me to add appNames for apps like LDPlayer (android emulator). I used the following appNames, but it didn't work.

`"appNames": ["LDPlayer9", "D:\\LDPlayer\\LDPlayer9\\LDPlayer.exe", "LDPlayer9.exe", "LDPlayer.exe"],`

**Comment by wiresock** [comment]
I recommend beginning by verifying the exact process name and ensuring that Proxifyre has the necessary access rights to track its connections. Consider operating Proxifyre as a Windows service under the SYSTEM account to gain full access to all process details.

**Comment by ashik4u** [comment]
Sorry for the late response. I'll try and let you know by today
