### ISSUE TITLE
Can`t run it

### ISSUE THREAD

**Issue by SaymanNsk** [wiresock/proxifyre#42]
Hello. I try to run proxifyre with next app-conf.json:
{
 "logLevel": "None",
 "proxies": [
         {
         "appNames": ["LDPlayer9", "C:\\Program Files\\ldplayer9box\\Ld9BoxHeadless.exe"],
         "socks5ProxyEndpoint": "185.158.114.14:34075",
         "username": "",
         "password": "",
         "supportedProtocols": ["TCP", "UDP"]
         }
     ]
}

but have errors:
Topshelf v4.3.0.0, .NET Framework 4.8.9261.0 (4.0.30319.42000)
Topshelf.Hosts.ConsoleRunHost Error: 0 : An exception occurred, System.Runtime.InteropServices.SEHException (0x80004005): Внешний компонент создал исключение.
   в socksify_unmanaged.get_instance(log_level_mx )
   в Socksifier.Socksifier..ctor(LogLevel log_level)
   в Socksifier.Socksifier.GetInstance(LogLevel log_level)
   в ProxiFyre.ProxiFyreService.Start()
   в Topshelf.ServiceConfiguratorExtensions.<>c__DisplayClass2_0`1.<WhenStarted>b__0(T service, HostControl control)
   в Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   в Topshelf.Hosts.ConsoleRunHost.Run()
Topshelf.Hosts.ConsoleRunHost Critical: 0 : The service threw an unhandled exception, System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в System.Threading.EventWaitHandle.Set()
   в Socksifier.Socksifier.!Socksifier()
   в Socksifier.Socksifier.Dispose(Boolean A_0)

Необработанное исключение: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в System.Threading.EventWaitHandle.Set()
   в Socksifier.Socksifier.!Socksifier()
   в Socksifier.Socksifier.Dispose(Boolean A_0)

**Comment by wiresock** [comment]
Have you installed [Windows Packet Filter](https://github.com/wiresock/ndisapi/releases)?

**Comment by RightFS** [comment]
you can try my fork, I did some work to make it easy.  https://github.com/RightFS/proxifyre

**Comment by Benzinnos** [comment]
Same issue. Windows Packet Filter has been installed. I did some research, socksify example from NDISAPI works well, but proxifyre closing immediately.

**Comment by wiresock** [comment]
It’s likely a .NET-related issue. Do you have the required .NET version installed?
